version: '2'
services:
  els1:
    build:
      context: ./
      dockerfile: Dockerfile-els
    ports:
    - "9200:9200"
    volumes:
    - ./data:/usr/share/elasticsearch/data
    networks:
      - mynet
    container_name: els1
    hostname: els1
    command: elasticsearch -Des.discovery.zen.ping.unicast.hosts=els1
  els2:
    build:
      context: ./
      dockerfile: Dockerfile-els
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - mynet
    container_name: els2
    hostname: els2
    command: elasticsearch -Des.discovery.zen.ping.unicast.hosts=els1
  kibana:
    build:
      context: ./
      dockerfile: Dockerfile-kibana
    ports:
      - "5601:5601"
    networks:
      - mynet
    environment:
      ELASTICSEARCH_URL: http://els1:9200
    container_name: kibana
    hostname: Kibana
networks:
  mynet:
