version: '2'
services:
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile-els
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./data:/usr/share/elasticsearch/data
    networks:
      - mynet
    container_name: elasticsearch
  kibana:
    build:
      context: ./
      dockerfile: Dockerfile-kibana
    ports:
      - "5601:5601"
    networks:
      - mynet
    container_name: kibana
networks:
  mynet:
